feature(autocomplete): Pass the `raw` OLS value to a client via selectionChangedEvent (i.e. the real label).
nfdi4health/semlookp-widgets pull request #17
Opened 2023-07-27 15:32 UTC by johannes-darms

This further hides transformation for display purposes within the component. Either just labels are used for rendering or a complex representation is chosen. Behavior is controlled via the boolean `props.hasShortSelectedLabel` parameter

2023-07-27 15:36 UTC, johannes-darms commented
If a client needs the concatenated version of the label, it can be generated with the given properties. This allows client to further work with the original value, without substring invocation.

2023-07-28 07:07 UTC, jusa3 requested changes

2023-07-28 07:36 UTC, johannes-darms commented on src/components/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> -            <EuiHealth title={value.type} color={dotColor}>
Yes, this is a feature we need once #15 and #14 are resolved, than the list of available concepts is well defined and we can remove the complexity of showing the ontology information. Additionally, I have no clue what the color coding should tell a user, explanatory information/cues are missing in the UI.

Nevertheless, this behavior change is better controlled by a different property than the `hasShortSelectedLabel`. I also have use cases where I need the shortLabel but the ontologyname during selection, which is not possible with this implementation. I will push an update later today.

2023-07-28 07:54 UTC, johannes-darms commented on src/components/widgets/AutocompleteWidget/AutocompleteWidget.tsx
> -            <EuiHealth title={value.type} color={dotColor}>
@jusa3 in [1c7aadc](https://github.com/nfdi4health/semlookp-widgets/pull/17/commits/1c7aadc4eba9ef888732431556e1fe5e22400bbb) I removed that section and the complex color version during selection is always shown. We can change the behavior of that part in another PR.

2023-07-28 09:38 UTC, merged